development: &default
  adapter: postgresql
  encoding: unicode
  database: findit
  pool: 5
  username: db
  password: db
  host: db


test: &test
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

<%= file = File.join("config", "database.local.yml")
  IO.read(file) if File.exist?(file) %>
